### ISSUE TITLE
Unable to compile the source

### ISSUE THREAD

**Issue by eisnerguy1** [mdsteele/big2small#1]
So, I'm trying to compile the latest source. I've to RGBDS installed:
"brew info rgbds               
==> rgbds: stable 0.6.1 (bottled), HEAD
Rednex GameBoy Development System
https://rgbds.gbdev.io
/usr/local/Cellar/rgbds/0.6.1 (29 files, 1.5MB) *
  Poured from bottle on 2023-01-12 at 15:53:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/rgbds.rb
License: MIT
==> Dependencies
Build: bison ✔, cmake ✔, pkg-config ✔, rust ✘
Required: libpng ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 170 (30 days), 566 (90 days), 1,223 (365 days)
install-on-request: 170 (30 days), 566 (90 days), 1,223 (365 days)
build-error: 6 (30 days)"

Yet, when I run the "make" command, I get a bunch of syntax errors:
"make
Compiling src/puzzle.asm
error: src/puzzle.asm(20) -> src/hardware.inc(32):
    syntax error, unexpected set
error: src/puzzle.asm(20) -> src/hardware.inc(34): [-Werror=obsolete]
    `rev_Check_hardware_inc: MACRO` is deprecated; use `MACRO rev_Check_hardware_inc`
error: src/puzzle.asm(20) -> src/hardware.inc(901): [-Werror=obsolete]
    `NINTENDO_LOGO: MACRO` is deprecated; use `MACRO NINTENDO_LOGO`
error: src/puzzle.asm(21) -> src/macros.inc(28): [-Werror=obsolete]
    `if_eq: MACRO` is deprecated; use `MACRO if_eq`
error: src/puzzle.asm(21) -> src/macros.inc(50): [-Werror=obsolete]
    `if_ne: MACRO` is deprecated; use `MACRO if_ne`
error: src/puzzle.asm(21) -> src/macros.inc(72): [-Werror=obsolete]
    `if_lt: MACRO` is deprecated; use `MACRO if_lt`
error: src/puzzle.asm(21) -> src/macros.inc(94): [-Werror=obsolete]
    `if_ge: MACRO` is deprecated; use `MACRO if_ge`
error: src/puzzle.asm(21) -> src/macros.inc(115): [-Werror=obsolete]
    `if_cgb: MACRO` is deprecated; use `MACRO if_cgb`
error: src/puzzle.asm(21) -> src/macros.inc(134): [-Werror=obsolete]
    `if_dmg: MACRO` is deprecated; use `MACRO if_dmg`
error: src/puzzle.asm(21) -> src/macros.inc(156): [-Werror=obsolete]
    `deref: MACRO` is deprecated; use `MACRO deref`
error: src/puzzle.asm(21) -> src/macros.inc(180): [-Werror=obsolete]
    `ldb: MACRO` is deprecated; use `MACRO ldb`
error: src/puzzle.asm(21) -> src/macros.inc(195): [-Werror=obsolete]
    `ldw: MACRO` is deprecated; use `MACRO ldw`
error: src/puzzle.asm(21) -> src/macros.inc(212): [-Werror=obsolete]
    `mult: MACRO` is deprecated; use `MACRO mult`
error: src/puzzle.asm(21) -> src/macros.inc(230): [-Werror=obsolete]
    `neg: MACRO` is deprecated; use `MACRO neg`
error: src/puzzle.asm(21) -> src/macros.inc(248): [-Werror=obsolete]
    `romb: MACRO` is deprecated; use `MACRO romb`
error: src/puzzle.asm(21) -> src/macros.inc(263): [-Werror=obsolete]
    `xld: MACRO` is deprecated; use `MACRO xld`
error: src/puzzle.asm(21) -> src/macros.inc(281): [-Werror=obsolete]
    `xcall: MACRO` is deprecated; use `MACRO xcall`
error: src/puzzle.asm(21) -> src/macros.inc(299): [-Werror=obsolete]
    `zcall: MACRO` is deprecated; use `MACRO zcall`
error: src/puzzle.asm(21) -> src/macros.inc(311): [-Werror=obsolete]
    `COPY_FROM_CURR: MACRO` is deprecated; use `MACRO COPY_FROM_CURR`
error: src/puzzle.asm(21) -> src/macros.inc(324): [-Werror=obsolete]
    `COPY_FROM_ROMX: MACRO` is deprecated; use `MACRO COPY_FROM_ROMX`
error: src/puzzle.asm(21) -> src/macros.inc(341): [-Werror=obsolete]
    `COPY_FROM_ROM0: MACRO` is deprecated; use `MACRO COPY_FROM_ROM0`
error: src/puzzle.asm(21) -> src/macros.inc(354): [-Werror=obsolete]
    `COPY_FROM_SAME: MACRO` is deprecated; use `MACRO COPY_FROM_SAME`
error: src/puzzle.asm(21) -> src/macros.inc(367): [-Werror=obsolete]
    `PLAY_SFX1: MACRO` is deprecated; use `MACRO PLAY_SFX1`
error: src/puzzle.asm(21) -> src/macros.inc(379): [-Werror=obsolete]
    `PLAY_SFX4: MACRO` is deprecated; use `MACRO PLAY_SFX4`
error: src/puzzle.asm(21) -> src/macros.inc(391): [-Werror=obsolete]
    `PLAY_SONG: MACRO` is deprecated; use `MACRO PLAY_SONG`
error: Assembly aborted (1 error)!
make: *** [out/obj/puzzle.o] Error 1"

Am I missing something?

**Comment by mdsteele** [comment]
Hmm, it looks like I've been using rgbasm v0.4.1.  Apparently the assembler syntax has changed in more recent versions?  I probably need to update my code.

In the meantime, you might be able to get it to build with the newer version of RGBDS by removing the `-Werror` flag from the `Makefile`, and maybe also replacing `src/hardware.inc` with a [more recent version](https://github.com/gbdev/hardware.inc).

**Comment by eisnerguy1** [comment]
Both those suggestions worked!
![big2small-0](https://user-images.githubusercontent.com/3295271/212274541-32a17ec6-08f1-47b5-bf3e-30d0b344e778.png) ![big2small-1](https://user-images.githubusercontent.com/3295271/212274543-5be04c57-c326-48af-a447-26cd71798300.png)

Thanks! 😄 👍🏻
